sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "2.0.0"
  - "1.8.1"
branches:
  only:
    - master
notifications:
  email:
    - snowyu.lee@gmail.com
script: npm test

before_install:
  - export JOBS=max
  - npm install -g npm@latest
  - npm install -g coffee-script

