os:
  - linux
  - osx
sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
branches:
  only:
    - master
notifications:
  email:
    - snowyu.lee@gmail.com
before_install:
  - export JOBS=max
  - npm install -g coffee-script
script: npm test


